from .api import acad_dll

from .doc import AcadDocument, AcadDocuments
from .utils import _ez_ptr
from .enums import (
    AcWindowState,
    AcZoomScaleType,
)
from .stubs import (
    A3Point,
    AcadMenuBar,
    AcadMenuGroups,
    AcadPreferences,
    AcadState,
    AcadViewport,
)

_dll = acad_dll.dll

class AcadApplication(POINTER(_dll.IAcadApplication), _ez_ptr):
    def __new__(cls: Any, create_if_not_exists: bool=True, always_new: bool=False, visible: bool=True, sink: Any=None) -> AcadApplication: ...
    def eval(self, Expression: str) -> None: ...
    def getacadstate(self) -> AcadState: ...
    def getinterfaceobject(self, ProgID: str) -> Any: ...
    def listarx(self) -> Any: ...
    def loadarx(self, Name: str) -> None: ...
    def loaddvb(self, Name: str) -> None: ...
    def quit(self) -> None: ...
    def runmacro(self, MacroPath: str) -> None: ...
    def unloadarx(self, Name: str) -> None: ...
    def unloaddvb(self, Name: str) -> None: ...
    def Update(self) -> None: ...
    def ZoomAll(self) -> None: ...
    def ZoomCenter(self, Center: A3Point, Magnify: float) -> None: ...
    def ZoomExtents(self) -> None: ...
    def ZoomPickWindow(self) -> None: ...
    def ZoomPrevious(self) -> None: ...
    def ZoomScaled(self, scale: float, ScaleType: AcZoomScaleType) -> None: ...
    def ZoomWindow(self, LowerLeft: A3Point, UpperRight: A3Point) -> None: ...
    @property
    def activedocument(self) -> AcadDocument: ...
    @property
    def application(self) -> AcadApplication: ...
    @property
    def caption(self) -> str: ...
    @property
    def documents(self) -> AcadDocuments: ...
    @property
    def fullname(self) -> str: ...
    @property
    def height(self) -> int: ...
    @property
    def hwnd(self) -> int: ...
    @property
    def localeid(self) -> int: ...
    @property
    def menubar(self) -> AcadMenuBar: ...
    @property
    def menugroups(self) -> AcadMenuGroups: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def preferences(self) -> AcadPreferences: ...
    @property
    def statusid(self, VportObj: AcadViewport) -> bool: ...
    @property
    def vbe(self) -> Any: ...
    @property
    def version(self) -> str: ...
    @property
    def visible(self) -> bool: ...
    @property
    def width(self) -> int: ...
    @property
    def windowleft(self) -> int: ...
    @property
    def windowstate(self) -> AcWindowState: ...
    @property
    def windowtop(self) -> int: ...
